#!/usr/bin/env bash

function print_usage(){
  echo "Usage: build source-file [option]"
  echo "       where option is one of:"
  echo "  export               export header file"
}

if [ $# = 0 ]; then
  print_usage
  exit
fi

if [ ! -f mloop.mlb ]; then
  touch mloop.mlb
fi
cat mloop_.mlb > mloop.mlb
echo "$1" >> mloop.mlb

if [ "$2" = "export" ]; then
  mlton -default-ann 'allowFFI true' -export-header export.h -stop tc mloop.mlb
else
  make mloop
  mlton -default-ann 'allowFFI true' -link-opt '-L/home/hadoop-2.2.0/lib/native -luuid -lstdc++ -lpthread -lcrypto -lhdfs' mloop.mlb serial.o utils.o pipes.o HadoopPipes.o SerialUtils.o StringUtils.o HadoopPipes_cpp.o hdfs_fs.o
fi


